(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),toast=document.getElementById('toast');
const W=960,H=480,T=24,ROWS=20;
canvas.width=W;canvas.height=H;
const types={0:{name:'Ar'},1:{name:'Grama',color:'#6eaa43'},2:{name:'Terra',color:'#94603e'},3:{name:'Pedra',color:'#818b8d'},4:{name:'Madeira',color:'#936039'},5:{name:'Folhas',color:'#3f883e'},6:{name:'Areia',color:'#d8c27a'},7:{name:'Tijolos',color:'#b66b4a'},8:{name:'Minério de cobre',color:'#c47a48'},9:{name:'Minério de ferro',color:'#c6c9c4'},10:{name:'Minério de ouro',color:'#f0c94d'}};
const palette=[1,2,3,4,5,6,7,8,9,10],inventory={1:12,2:24,3:8,4:10,5:8,6:8,7:0,8:0,9:0,10:0};let toolLevel=0,toolName='Mãos';
let world=new Map(),generated=new Set(),camera=0,selected=1,day=0,health=10,keys={},last=0,seed=Math.floor(Math.random()*1e9);
const player={x:120,y:100,w:16,h:35,vx:0,vy:0,onGround:false,face:1};
function rand(n){let x=Math.sin(n*127.1+seed*.001)*43758.5453;return x-Math.floor(x)}
function heightAt(x){return Math.max(7,Math.min(13,10+Math.round(Math.sin(x*.13)*2+Math.sin(x*.037)*2+Math.sin(x*.31))))}
function key(x,y){return x+','+y}
function setBlock(x,y,id){if(y>=0&&y<ROWS){if(id)world.set(key(x,y),id);else world.delete(key(x,y))}}
function generateColumn(x){if(generated.has(x))return;generated.add(x);let h=heightAt(x);for(let y=h;y<ROWS;y++){let id=y===h?1:y<h+4?2:3;if(y>=h+5&&y<ROWS-1){let ore=rand(x*31+y*17);if(ore<.035)id=8;else if(ore<.058)id=9;else if(y>=16&&ore<.073)id=10;}setBlock(x,y,id)}if(rand(x)<.13)setBlock(x,h+1,6);if(rand(x+91)>.88&&h>7){for(let k=1;k<=3;k++)setBlock(x,h-k,5);for(let dx=-2;dx<=2;dx++)for(let dy=-3;dy<=-2;dy++)if(Math.abs(dx)+Math.abs(dy)<5) setBlock(x+dx,h+dy,5);setBlock(x,h-1,4)}}
function ensureRange(a,b){for(let x=Math.floor(a);x<=Math.ceil(b);x++)generateColumn(x)}
function block(x,y){if(y<0)return 0;if(y>=ROWS)return 3;generateColumn(x);return world.get(key(x,y))||0}
function solid(x,y){return block(x,y)!==0}
function notify(s){toast.textContent=s;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),1700)}
function drawBlock(x,y,id){const px=x*T-camera,py=y*T;const colors={1:'#98633f',2:'#98633f',3:'#7d888b',4:'#976039',5:'#3d873d',6:'#d8c27a',7:'#b66b4a',8:'#98603b',9:'#777d7d',10:'#b88c28'};ctx.fillStyle=colors[id]||'#000';ctx.fillRect(px,py,T,T);if(id===1){ctx.fillStyle='#6cab43';ctx.fillRect(px,py,T,7);ctx.fillStyle='#82c454';ctx.fillRect(px,py,T,2);ctx.fillStyle='#75472f';ctx.fillRect(px+5,py+11,4,3);ctx.fillRect(px+16,py+17,3,4)}else if(id===2){ctx.fillStyle='#75472f';ctx.fillRect(px+5,py+7,4,3);ctx.fillRect(px+16,py+15,4,3);ctx.fillStyle='#b27a4d';ctx.fillRect(px+11,py+20,3,2)}else if(id===3){ctx.fillStyle='#9ba5a6';ctx.fillRect(px+3,py+4,7,3);ctx.fillRect(px+15,py+14,5,4);ctx.fillStyle='#657174';ctx.fillRect(px+4,py+17,5,3)}else if(id===4){ctx.fillStyle='#bd8750';ctx.fillRect(px+5,py,3,T);ctx.fillRect(px+16,py,2,T);ctx.fillStyle='#75472c';ctx.fillRect(px+10,py,2,T)}else if(id===5){ctx.fillStyle='#56a64b';ctx.fillRect(px+3,py+3,7,6);ctx.fillRect(px+15,py+12,6,7);ctx.fillStyle='#347638';ctx.fillRect(px+9,py+16,5,5)}else if(id===6){ctx.fillStyle='#eadb9c';ctx.fillRect(px+4,py+5,5,2);ctx.fillRect(px+16,py+15,4,2)}else if(id===7){ctx.fillStyle='#d9946c';for(let yy=4;yy<24;yy+=10){ctx.fillRect(px+2,py+yy,9,5);ctx.fillRect(px+14,py+yy,8,5)}}else if(id>=8){ctx.fillStyle=id===8?'#d98b50':id===9?'#d5d8d3':'#ffe16a';for(let i=0;i<5;i++){let ox=3+Math.floor(rand(x*71+y*19+i)*17),oy=3+Math.floor(rand(x*29+y*43+i)*17);ctx.fillRect(px+ox,py+oy,4,4)}}}
function draw(){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,day%2?'#172c50':'#78c8ef');sky.addColorStop(1,day%2?'#566e87':'#d3edee');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=day%2?'#e5e9ed':'#fff2b0';ctx.beginPath();ctx.arc(790,day%2?75:72,day%2?18:25,0,Math.PI*2);ctx.fill();for(let i=0;i<7;i++){let x=((i*177-camera*.18)%(W+150)+W+150)%(W+150)-70,y=60+(i%3)*37;ctx.fillStyle=day%2?'#9eafbd':'#ffffff66';ctx.fillRect(x,y,52,10);ctx.fillRect(x+12,y-9,30,10);ctx.fillRect(x+38,y+3,23,7)}
let start=Math.floor(camera/T)-1,end=Math.ceil((camera+W)/T)+1;ensureRange(start,end);for(let x=start;x<=end;x++)for(let y=0;y<ROWS;y++){let id=block(x,y);if(id)drawBlock(x,y,id);if(y===heightAt(x)&&id===1&&rand(x+500)>.77){ctx.fillStyle=rand(x+501)>.5?'#f5d35c':'#e7e9e7';ctx.fillRect(x*T-camera+10,y*T-5,3,3)}}
let px=player.x-camera,py=player.y;ctx.fillStyle='#26384b';ctx.fillRect(px+3,py+14,11,19);ctx.fillStyle='#d9a276';ctx.fillRect(px+3,py+2,12,13);ctx.fillStyle='#4c3027';ctx.fillRect(px+2,py,14,5);ctx.fillStyle='#e9e8d9';ctx.fillRect(px+5,py+18,4,5);ctx.fillRect(px+12,py+18,3,5);ctx.fillStyle='#3c5069';ctx.fillRect(px+2,py+31,5,4);ctx.fillRect(px+11,py+31,5,4);ctx.fillStyle='#26313b';ctx.fillRect(px+(player.face>0?12:4),py+7,2,2);
if(lastMouse.x>=0){let tx=Math.floor((lastMouse.x+camera)/T),ty=Math.floor(lastMouse.y/T);if(ty>=0&&ty<ROWS){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(tx*T-camera+1,ty*T+1,T-2,T-2)}}
document.getElementById('coords').textContent=Math.floor(player.x/T)+', '+Math.floor(player.y/T);document.getElementById('time').textContent=day%2?'Noite':'Dia';}
function collide(x,y,w,h){let l=Math.floor(x/T),r=Math.floor((x+w-1)/T),t=Math.floor(y/T),b=Math.floor((y+h-1)/T);for(let yy=t;yy<=b;yy++)for(let xx=l;xx<=r;xx++)if(solid(xx,yy))return true;return false}
function physics(dt){let speed=170;player.vx=(keys.KeyA||keys.ArrowLeft?-speed:0)+(keys.KeyD||keys.ArrowRight?speed:0);if(player.vx)player.face=Math.sign(player.vx);if((keys.Space||keys.KeyW||keys.ArrowUp)&&player.onGround){player.vy=-390;player.onGround=false}player.vy=Math.min(650,player.vy+1050*dt);let nx=player.x+player.vx*dt;if(!collide(nx,player.y,player.w,player.h))player.x=nx;let ny=player.y+player.vy*dt;if(!collide(player.x,ny,player.w,player.h)){player.y=ny;player.onGround=false}else{if(player.vy>0)player.onGround=true;player.vy=0}if(player.y>H){player.x-=80;player.y=40;player.vy=0;health=Math.max(1,health-1);document.getElementById('health').textContent=health}camera=player.x-W*.42}
function loop(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;physics(dt);draw();requestAnimationFrame(loop)}
const lastMouse={x:-1,y:-1};function mousePos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointermove',e=>{let p=mousePos(e);lastMouse.x=p.x;lastMouse.y=p.y});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();let p=mousePos(e),tx=Math.floor((p.x+camera)/T),ty=Math.floor(p.y/T);if(ty<0||ty>=ROWS)return;let dx=tx*T+T/2-(player.x+player.w/2),dy=ty*T+T/2-(player.y+player.h/2);if(Math.hypot(dx,dy)>T*5){notify('Chegue mais perto do bloco.');return}if(e.button===2){if(block(tx,ty)!==0||!inventory[selected])return;if(Math.floor(player.x/T)===tx&&Math.floor((player.x+player.w-1)/T)===tx&&Math.floor(player.y/T)<=ty&&Math.floor((player.y+player.h-1)/T)>=ty)return;setBlock(tx,ty,selected);inventory[selected]--;renderBar()}else{let id=block(tx,ty);if(!id)return;if((id===3||id===8||id===9||id===10)&&toolLevel<1){notify('Fabrique uma picareta de madeira para minerar pedra e minérios.');return}if((id===9||id===10)&&toolLevel<2){notify('Precisa de uma picareta de pedra para este minério.');return}if(id===10&&toolLevel<3){notify('Precisa de uma picareta de ferro para minerar ouro.');return}setBlock(tx,ty,0);inventory[id]=(inventory[id]||0)+1;renderBar()}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(/^Digit[1-9]$/.test(e.code)){selected=palette[Number(e.code.slice(-1))-1];renderBar()}if(e.code==='Digit0'){selected=10;renderBar()}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>keys={});
function renderBar(){let bar=document.getElementById('hotbar');bar.innerHTML='';palette.forEach((id,i)=>{let s=document.createElement('button');s.className='slot'+(id===selected?' selected':'');s.setAttribute('aria-label',(i+1)+': '+types[id].name+', '+(inventory[id]||0));s.innerHTML='<span class="key">'+(i+1)+'</span><canvas width="30" height="30"></canvas><span class="count">'+(inventory[id]||0)+'</span>';let c=s.querySelector('canvas').getContext('2d');c.fillStyle=types[id].color;c.fillRect(2,2,26,26);if(id===1){c.fillStyle='#6cab43';c.fillRect(2,2,26,7)}if(id===7){c.fillStyle='#d9946c';c.fillRect(4,7,9,5);c.fillRect(16,17,9,5)}s.onclick=()=>{selected=id;renderBar()};bar.appendChild(s)})}
const recipes=[{id:7,name:'Tijolos (4)',cost:{2:4,3:1},out:4},{tool:1,name:'Picareta de madeira',cost:{4:3},requires:0},{tool:2,name:'Picareta de pedra',cost:{4:2,3:5},requires:1},{tool:3,name:'Picareta de ferro',cost:{4:2,9:3},requires:2}];
function renderCraft(){let el=document.getElementById('recipes');el.innerHTML='';recipes.forEach(r=>{let b=document.createElement('button');b.className='recipe';let costs=Object.entries(r.cost).map(([id,n])=>n+' '+types[id].name).join(' + ');b.innerHTML='<strong>'+(r.tool?'⛏️ ':'🧱 ')+r.name+'</strong><small>'+costs+'</small>';b.onclick=()=>{if(r.tool&&toolLevel!==r.requires){notify('Fabrique primeiro a ferramenta anterior.');return}if(Object.entries(r.cost).some(([id,n])=>(inventory[id]||0)<n)){notify('Recursos insuficientes para fabricar.');return}Object.entries(r.cost).forEach(([id,n])=>inventory[id]-=n);if(r.tool){toolLevel=r.tool;toolName=r.name;document.getElementById('tool-status').textContent='Ferramenta: '+toolName}else inventory[r.id]=(inventory[r.id]||0)+r.out;renderBar();notify(r.tool?'Ferramenta fabricada e equipada!':'Item fabricado!')};el.appendChild(b)})}
function save(){let data={world:[...world.entries()],generated:[...generated],player:{x:player.x,y:player.y},inventory,selected,day,seed,toolLevel};try{localStorage.setItem('block-world',JSON.stringify(data));notify('Mundo salvo neste navegador.')}catch(e){notify('Não foi possível salvar: armazenamento cheio.')}}function load(){try{let s=JSON.parse(localStorage.getItem('block-world'));if(s&&s.player){world=new Map(s.world||[]);generated=new Set(s.generated||[]);Object.assign(player,s.player);Object.assign(inventory,s.inventory||{});selected=s.selected||1;day=s.day||0;seed=s.seed||seed;toolLevel=s.toolLevel||0;toolName=['Mãos','Picareta de madeira','Picareta de pedra','Picareta de ferro'][toolLevel]||'Mãos';document.getElementById('tool-status').textContent='Ferramenta: '+toolName;return true}}catch(e){}return false}
document.getElementById('save').onclick=save;document.getElementById('reset').onclick=()=>{if(confirm('Criar um mundo novo? O mundo salvo atual será substituído.')){localStorage.removeItem('block-world');location.reload()}};window.addEventListener('beforeunload',()=>{try{localStorage.setItem('block-world',JSON.stringify({world:[...world.entries()],generated:[...generated],player:{x:player.x,y:player.y},inventory,selected,day,seed,toolLevel}))}catch(e){}});
renderCraft();if(!load()){ensureRange(-10,50);player.y=(heightAt(5)-2)*T}ensureRange(-10,60);renderBar();requestAnimationFrame(loop);
})();