(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),toast=document.getElementById('toast');
const W=960,H=480,T=24,ROWS=20,COLS=40;
canvas.width=W;canvas.height=H;
const types={0:{name:'Ar',color:null},1:{name:'Grama',color:'#6eaa43'},2:{name:'Terra',color:'#94603e'},3:{name:'Pedra',color:'#818b8d'},4:{name:'Madeira',color:'#936039'},5:{name:'Folhas',color:'#3f883e'},6:{name:'Areia',color:'#d8c27a'}};
const palette=[1,2,3,4,5,6],inventory={1:12,2:24,3:8,4:10,5:8,6:8};
let world=[],surface=[],camera=0,selected=1,day=0,health=10,keys={},last=0,saveTick=0;
const player={x:120,y:100,w:16,h:35,vx:0,vy:0,onGround:false,face:1};
let seed=Math.floor(Math.random()*1e9);
function rand(n){let x=Math.sin(n*127.1+seed*.001)*43758.5453;return x-Math.floor(x)}
function heightAt(x){return Math.max(7,Math.min(13,10+Math.round(Math.sin(x*.13)*2+Math.sin(x*.037)*2+Math.sin(x*.31))))}
function generate(){world=Array.from({length:ROWS},()=>Array(COLS).fill(0));surface=[];for(let x=0;x<COLS;x++){let h=heightAt(x);surface[x]=h;for(let y=h;y<ROWS;y++){world[y][x]=y===h?1:y<h+4?2:3;if(y===h+1&&rand(x)<.13)world[y][x]=6;}if(rand(x+91)>.88&&h>7){for(let k=1;k<=3;k++)if(h-k>=0)world[h-k][x]=5;if(x>1&&x<COLS-2){world[h-3][x-1]=5;world[h-3][x+1]=5;world[h-2][x-1]=5;world[h-2][x+1]=5;world[h-4][x]=5;}world[h-1][x]=4;}}}
function block(x,y){return y<0?0:y>=ROWS?3:x<0||x>=COLS?3:world[y][x]}
function solid(x,y){return block(x,y)!==0}
function notify(s){toast.textContent=s;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),1500)}
function resize(){/* Canvas uses a fixed logical resolution and scales crisply. */}
function drawBlock(x,y,id){const px=x*T-camera,py=y*T;if(id===1){ctx.fillStyle='#98633f';ctx.fillRect(px,py,T,T);ctx.fillStyle='#6cab43';ctx.fillRect(px,py,T,7);ctx.fillStyle='#82c454';ctx.fillRect(px,py,T,2);ctx.fillStyle='#75472f';ctx.fillRect(px+5,py+11,4,3);ctx.fillRect(px+16,py+17,3,4)}else if(id===2){ctx.fillStyle='#98633f';ctx.fillRect(px,py,T,T);ctx.fillStyle='#75472f';ctx.fillRect(px+5,py+7,4,3);ctx.fillRect(px+16,py+15,4,3);ctx.fillStyle='#b27a4d';ctx.fillRect(px+11,py+20,3,2)}else if(id===3){ctx.fillStyle='#7d888b';ctx.fillRect(px,py,T,T);ctx.fillStyle='#9ba5a6';ctx.fillRect(px+3,py+4,7,3);ctx.fillRect(px+15,py+14,5,4);ctx.fillStyle='#657174';ctx.fillRect(px+4,py+17,5,3)}else if(id===4){ctx.fillStyle='#976039';ctx.fillRect(px,py,T,T);ctx.fillStyle='#bd8750';ctx.fillRect(px+5,py,3,T);ctx.fillRect(px+16,py,2,T);ctx.fillStyle='#75472c';ctx.fillRect(px+10,py,2,T)}else if(id===5){ctx.fillStyle='#3d873d';ctx.fillRect(px,py,T,T);ctx.fillStyle='#56a64b';ctx.fillRect(px+3,py+3,7,6);ctx.fillRect(px+15,py+12,6,7);ctx.fillStyle='#347638';ctx.fillRect(px+9,py+16,5,5)}else if(id===6){ctx.fillStyle='#d8c27a';ctx.fillRect(px,py,T,T);ctx.fillStyle='#eadb9c';ctx.fillRect(px+4,py+5,5,2);ctx.fillRect(px+16,py+15,4,2)}}
function draw(){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,day%2?'#172c50':'#78c8ef');sky.addColorStop(1,day%2?'#566e87':'#d3edee');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
ctx.fillStyle=day%2?'#e5e9ed':'#fff2b0';ctx.beginPath();ctx.arc(day%2?790:790,day%2?75:72,day%2?18:25,0,Math.PI*2);ctx.fill();
for(let i=0;i<7;i++){let x=((i*177-camera*.18)%(W+150)+W+150)%(W+150)-70;let y=60+(i%3)*37;ctx.fillStyle=day%2?'#9eafbd':'#ffffff66';ctx.fillRect(x,y,52,10);ctx.fillRect(x+12,y-9,30,10);ctx.fillRect(x+38,y+3,23,7)}
const start=Math.max(0,Math.floor(camera/T)),end=Math.min(COLS,Math.ceil((camera+W)/T));for(let x=start;x<end;x++)for(let y=0;y<ROWS;y++){let id=block(x,y);if(id)drawBlock(x,y,id)}
// simple flowers
for(let x=start;x<end;x++)if(block(x,surface[x])===1&&rand(x+500)>.77){ctx.fillStyle=rand(x+501)>.5?'#f5d35c':'#e7e9e7';ctx.fillRect(x*T-camera+10,surface[x]*T-5,3,3)}
// player
const px=player.x-camera,py=player.y;ctx.fillStyle='#26384b';ctx.fillRect(px+3,py+14,11,19);ctx.fillStyle='#d9a276';ctx.fillRect(px+3,py+2,12,13);ctx.fillStyle='#4c3027';ctx.fillRect(px+2,py,14,5);ctx.fillStyle='#e9e8d9';ctx.fillRect(px+5,py+18,4,5);ctx.fillRect(px+12,py+18,3,5);ctx.fillStyle='#3c5069';ctx.fillRect(px+2,py+31,5,4);ctx.fillRect(px+11,py+31,5,4);ctx.fillStyle='#26313b';ctx.fillRect(px+(player.face>0?12:4),py+7,2,2);
const mx=lastMouse.x,my=lastMouse.y;if(mx>=0&&my>=0){let tx=Math.floor((mx+camera)/T),ty=Math.floor(my/T);if(tx>=0&&tx<COLS&&ty>=0&&ty<ROWS){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(tx*T-camera+1,ty*T+1,T-2,T-2)}}
document.getElementById('coords').textContent=Math.floor(player.x/T)+', '+Math.floor(player.y/T);document.getElementById('time').textContent=day%2?'Noite':'Dia';}
function collide(x,y,w,h){let l=Math.floor(x/T),r=Math.floor((x+w-1)/T),t=Math.floor(y/T),b=Math.floor((y+h-1)/T);for(let yy=t;yy<=b;yy++)for(let xx=l;xx<=r;xx++)if(solid(xx,yy))return true;return false}
function physics(dt){const speed=170;player.vx=(keys.KeyA||keys.ArrowLeft?-speed:0)+(keys.KeyD||keys.ArrowRight?speed:0);if(player.vx)player.face=Math.sign(player.vx);if((keys.Space||keys.KeyW||keys.ArrowUp)&&player.onGround){player.vy=-390;player.onGround=false}player.vy=Math.min(650,player.vy+1050*dt);let nx=player.x+player.vx*dt;if(!collide(nx,player.y,player.w,player.h))player.x=Math.max(0,Math.min(COLS*T-player.w,nx));let ny=player.y+player.vy*dt;if(!collide(player.x,ny,player.w,player.h)){player.y=ny;player.onGround=false}else{if(player.vy>0)player.onGround=true;player.vy=0}if(player.y>H){player.x=120;player.y=60;player.vy=0;health=Math.max(1,health-1);document.getElementById('health').textContent=health}camera=Math.max(0,Math.min(COLS*T-W,player.x-W*.42))}
function loop(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;physics(dt);draw();requestAnimationFrame(loop)}
const lastMouse={x:-1,y:-1};function mousePos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointermove',e=>{let p=mousePos(e);lastMouse.x=p.x;lastMouse.y=p.y});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();let p=mousePos(e),tx=Math.floor((p.x+camera)/T),ty=Math.floor(p.y/T);if(tx<0||tx>=COLS||ty<0||ty>=ROWS)return;let dx=tx*T+T/2-(player.x+player.w/2),dy=ty*T+T/2-(player.y+player.h/2);if(Math.hypot(dx,dy)>T*5){notify('Chegue mais perto do bloco.');return}if(e.button===2){if(block(tx,ty)!==0||!inventory[selected])return;world[ty][tx]=selected;inventory[selected]--;renderBar()}else{let id=block(tx,ty);if(!id)return;world[ty][tx]=0;if(id===1){inventory[2]=(inventory[2]||0)+1;inventory[1]=(inventory[1]||0)+1}else inventory[id]=(inventory[id]||0)+1;renderBar()}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(/^Digit[1-6]$/.test(e.code)){selected=palette[Number(e.code.slice(-1))-1];renderBar()}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>keys={});
function renderBar(){let bar=document.getElementById('hotbar');bar.innerHTML='';palette.forEach((id,i)=>{let s=document.createElement('button');s.className='slot'+(id===selected?' selected':'');s.setAttribute('aria-label',(i+1)+': '+types[id].name+', '+(inventory[id]||0));s.innerHTML='<span class="key">'+(i+1)+'</span><canvas width="30" height="30"></canvas><span class="count">'+(inventory[id]||0)+'</span>';let c=s.querySelector('canvas').getContext('2d');c.clearRect(0,0,30,30);c.fillStyle=types[id].color||'#000';c.fillRect(2,2,26,26);if(id===1){c.fillStyle='#6cab43';c.fillRect(2,2,26,7);c.fillStyle='#98633f';c.fillRect(2,9,26,19)}else if(id===2){c.fillStyle='#98633f';c.fillRect(2,2,26,26);c.fillStyle='#75472f';c.fillRect(7,8,5,3);c.fillRect(18,17,5,3)}else if(id===3){c.fillStyle='#9ba5a6';c.fillRect(5,6,7,4);c.fillRect(17,16,6,5)}else if(id===4){c.fillStyle='#bd8750';c.fillRect(7,2,4,26);c.fillRect(18,2,3,26)}else if(id===5){c.fillStyle='#56a64b';c.fillRect(5,5,8,7);c.fillRect(17,15,8,8)}else if(id===6){c.fillStyle='#eadb9c';c.fillRect(6,7,6,3);c.fillRect(18,17,6,3)}s.onclick=()=>{selected=id;renderBar()};bar.appendChild(s)})}
function save(){localStorage.setItem('block-world',JSON.stringify({world,surface,player:{x:player.x,y:player.y},inventory,selected,day,seed}));notify('Mundo salvo neste navegador.')}
function load(){try{let s=JSON.parse(localStorage.getItem('block-world'));if(s&&s.world&&s.world.length===ROWS){world=s.world;surface=s.surface;Object.assign(player,s.player);Object.assign(inventory,s.inventory);selected=s.selected||1;day=s.day||0;seed=s.seed||seed;return true}}catch(e){}return false}
document.getElementById('save').onclick=save;document.getElementById('reset').onclick=()=>{if(confirm('Criar um mundo novo? O mundo salvo atual será substituído.')){localStorage.removeItem('block-world');location.reload()}};window.addEventListener('beforeunload',()=>{try{localStorage.setItem('block-world',JSON.stringify({world,surface,player:{x:player.x,y:player.y},inventory,selected,day,seed}))}catch(e){}});
generate();if(!load())player.y=(surface[5]-2)*T;renderBar();requestAnimationFrame(loop);
})();